repos:
  - repo: https://github.com/mattybellx/Ansede
    rev: v2.1.6
    hooks:
      - id: ansede-static
        name: Ansede Static SAST
        language: python
        entry: ansede-static
        args: [--fail-on, high]
        types: [python, javascript, typescript]
        pass_filenames: false
        additional_dependencies: []
